### ISSUE TITLE
Lighthouse: Document does not have a valid rel=canonical Points to a different domain

### ISSUE THREAD

**Issue by NickyMeuleman** [NickCis/gatsby-plugin-react-helmet-canonical-urls#9]
disclaimer: not using this plugin but a similar method, added the canonical tag via React Helmet in a Gatsby site.
[great blogpost](https://nckweb.com.ar/gatsby-canonical-urls-react-helmet/), by the way!

Findings from my own site and this page:
https://nckweb.com.ar/jest-passing-custom-arguments/

In the `<head>`
![chrome_0RgNkDnTS3](https://user-images.githubusercontent.com/30179461/62414241-d6291e00-b618-11e9-80ef-cb0baaa33912.png)

When doing a Lighthouse audit (audit tab in google chrome devtools)
![chrome_Z2U6goMhLa](https://user-images.githubusercontent.com/30179461/62414244-f35dec80-b618-11e9-8905-43a7b61e2345.png)

How should one get around this? Apparently google support different domains, but Bing, Yahoo, ... don't.

[dev.to](https://dev.to/) also has support for canonical urls and they make it work somehow. Their canonical url in the `head` is just a link to their notifications page [example](https://dev.to/nickymeuleman/the-new-windows-terminal-271j)

**Comment by NickCis** [comment]
Hi, thanks for the information, I didn't notice this issue about canonicals.

This could be partly solved. In the case where you are hosting an external article (eg: [my jest passing custom arguments post](https://nckweb.com.ar/jest-passing-custom-arguments/)) the correct way should be directly linking the original article (you won't have the post on your site ) or perform a _Moved Permanent_ redirect (301) to the correct web page. I don't think that performing the redirection can be done with an static site generator (ie, Gatsby), you'll have to set that up on your hosting provider, if it allows it ([Zeit now](https://spectrum.chat/zeit/general/define-redirects-in-now-json~9830c866-3543-49c4-b55a-82e69078677d) and [Netlify](https://www.netlify.com/docs/redirects/) support writing a redirection file).

As you've said many sites supports setting up canonical url (medium also does using the [import a post ](https://help.medium.com/hc/en-us/articles/214550207-Import-a-post)) to a different domain. If you are concerned about being penalized by search engines because you are hosting content that is in another place (e.g: dev.to), I don't think that there is a way to solve this issue. Bare in mind that those platforms are choosing to ignore this issue and only support search engines that allow cross-domain canonical links.

**Comment by NickyMeuleman** [comment]
Thanks for the detailed response!

I'll consider it as "the way things are" and a cost of being able to cross-post blog articles.
On the search engine penalization part: google supporting it is the most important one.
Hopefully many other search engines that don't yet will in the future.

(this can be closed, since it's not really an issue, only an observation)

**Comment by NickCis** [comment]
You are welcome!
